### ISSUE TITLE
Add this repository to the GitHub.io link

### ISSUE THREAD

**Issue by joebayles** [Esri/military-tools-desktop-addins#10]
Add the tag `#Military-Tools-for-ArcGIS` to the README.

FYI @topowright

**Comment by csmoore** [comment]
That tag was there - what was the issue? Something to do with why the tags show up in the readme now (instead of being hidden):


![image](https://cloud.githubusercontent.com/assets/3090809/24161813/d2484b62-0e3b-11e7-8887-2cddb1e6bcf9.png)

**Comment by joebayles** [comment]
@csmoore I noticed that. I think that the issue is the commas, which is why I added them. I looked at a few and the ones who's tags were honored had commas. The issue now is that the github.io site hadn't been updated in a while. @alaframboise updated it, should be up shortly.
