### ISSUE TITLE
Addins are using the default addin icon

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-desktop-addins#101]
The Addin icon you see on the Pro Addin Manager page is still using the default addin icon, this should probably be changed to use the same icon we use on the Analysis Ribbon:

![image](https://user-images.githubusercontent.com/3090809/52490555-007eaf00-2b93-11e9-9975-7261bde80235.png)

![image](https://user-images.githubusercontent.com/3090809/52489774-22773200-2b91-11e9-8226-1311a73d9395.png)

This is also an issue with the individual addins.

**Comment by csmoore** [comment]
Icon changed in PR #101

![image](https://user-images.githubusercontent.com/3090809/59316306-c54cd380-8c8b-11e9-81e9-2c874abe8724.png)

**Comment by csmoore** [comment]
Sorry I forgot to do this for ArcMap also - ArcMap addin icons done in these PRs:

#114

**Comment by lfunkhouser** [comment]
verified as fixed in ArcMap with all add-ins.

Tested with ArcMap 10.6.1
