### ISSUE TITLE
Move Military Tools GP tools to the Military Tools ribbon

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-desktop-addins#103]
Based on feedback from FedGIS, users expect the Military Tools tools to be in one location. The GP tools were made available on the Analysis ribbon in MT 3.3. 

### Expected Behavior
All Military Tools tools are accessed from the Military Tools ribbon in ArcGIS Pro

### Current Behavior
Add-in components and functionality are in a single ribbon. The GP tools are on the Analysis ribbon.

### Your Environment
MT 3.3 January 2018 release
ArcGIS Pro 2.3

**Comment by BobBooth** [comment]
Probably should add it with a sub-title "Geoprocessing" since the GP tools have a very different interface from the add-in tools.
Maybe like this:
![image](https://user-images.githubusercontent.com/3801392/52743759-c48b8580-2fa8-11e9-96fd-3c05ea5006d7.png)

**Comment by csmoore** [comment]
Moving the GP tools button to the Military Tools tab was straightforward, however, unrelated to this I am having problems getting the GP tools to actually run at Pro 2.4 so looking into this issue:

![image](https://user-images.githubusercontent.com/3090809/58132485-6bf30680-7bef-11e9-9b0b-79ecd7331387.png)

**Comment by csmoore** [comment]
Submitted PR #111 with this change, ready for verify. Military Tools tab looks like this now:

![image](https://user-images.githubusercontent.com/3090809/58199880-779e0600-7c9f-11e9-842e-e0dc78322cf9.png)

**Comment by lfunkhouser** [comment]
@dfoll doesn't look like this was added yet to doc. Putting the CMS label on.

**Comment by dfoll** [comment]
@lfunkhouser you're right, i don't think it was... right now i do not recall how it was documented when this functionality was originally put in, on the analysis ribbon. depending on how we want to document this, this may be one of the more in-depth "workflow" doc tasks we discussed.

**Comment by lfunkhouser** [comment]
@dfoll The only place I see this documented currently is just in Release Notes for MT 3.3
No workflow currently exists - save that for a future release.
We should at minimum add it to What's new for MT 3.5

**Comment by lfunkhouser** [comment]
Verified on 3.5.0.307. Removing QC Verify label.

**Comment by dfoll** [comment]
- added to the mt june 2019 release page

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- https://solutionsdev.arcgis.com/defense/what-is-new/  (will require the 1200 pdt build to happen first)

**Comment by lfunkhouser** [comment]
@dfoll just realized it should be the "Military Tools" button not "Military Tools for ArcGIS" button

**Comment by lfunkhouser** [comment]
Verified release notes on solutionsdev and MT dev build 310

**Comment by lfunkhouser** [comment]
verified what's new on staging.
