### ISSUE TITLE
Create GitHub release of code supporting the MT 3.3.1 release

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-desktop-addins#104]
### Expected Behavior
Release created from Master branch. (require that dev be merged into Master first)
Tag with v3.3.1

### Your Environment

* Addin Version used: 
* Environment name and version (e.g. ArcMap 10.3, Pro 1.4):
* Operating System and version (desktop or mobile):
* Link to your project/test data (if applicable):

**Comment by csmoore** [comment]
Release created at: https://github.com/Esri/military-tools-desktop-addins/releases/tag/3.3.1
