### ISSUE TITLE
Add Dark Themed Icons

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-desktop-addins#11]
We have been provided Dark Themed Icons (zip below) - Pro desktop addins projects should be updated to add these icons.

[DarkIcons.zip](https://github.com/Esri/military-tools-desktop-addins/files/902663/DarkIcons.zip)

- [x] coordinate-conversion-addin-dotnet
- [x] distance-direction-addin-dotnet
- [x] military-symbol-editor-addin-wpf
- [x] visibility-addin-dotnet
- [x] military-tools-desktop-addins 

If needed there is a complete [Dark Theme SDK sample](https://github.com/Esri/arcgis-pro-sdk-community-samples/tree/master/Framework/CustomStyling)

**Comment by csmoore** [comment]
Dark icons added in PRs above, icons should look like this after PRs are merged:

![image](https://user-images.githubusercontent.com/3090809/26880719-5b08369c-4b63-11e7-9a88-9a80a52f9d97.png)

![image](https://user-images.githubusercontent.com/3090809/26880704-4c8054b0-4b63-11e7-90b8-d5d8922defbe.png)

**Comment by NatalieCampos** [comment]
This issue has been verified.
