### ISSUE TITLE
Military Toolbox as system tools in the add-in

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-desktop-addins#118]
Starting at Pro 2.4, Pro allows a system toolbox to be installed with a Pro addin. This eliminates the need to use Conda to install a system toolbox. Crime Analysis is using this method.

Doc
Pro 2.2-2.3 users: install toolbox using conda for tools to appear as system tools
Pro 2.4+ users: add-in will install tools as system tools

**Comment by csmoore** [comment]
PR #119 created to test

**Comment by dfoll** [comment]
### Repro steps
0. Install Military Tools for ArcGIS add-in (build 331)
1. Open ArcGIS Pro
2. Tools appear as system tools and behave
3. Clone a new Python environment
4. Make the new environment the active environment
5. Close Pro
6. Install the conda package
7. Open ArcGIS Pro (making sure you are using the environment you just installed MT to)

**Comment by csmoore** [comment]
That is a good catch. We can report this as an issue to Pro (installing a system toolbox both as an addin and conda causes neither to work).

But we may want to decide whether or not we just want to deprecate the Conda package or doc a warning that the conda package is only for use when the Addin is not installed.

**Comment by dfoll** [comment]
### Doc QC 
- [ ] [Military Tools  Get Started](https://solutions.arcgis.com/defense/help/military-tools/get-started/military-tools-for-arcgis-get-started.htm)
- [ ] [Military Tools October Resources]()
- [ ] \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\336\
- [Defense Whats new]() -- after [PR 8017](https://github.com/ArcGIS/arcgis-solutions-website/pull/8017) is reviewed and merged

**Comment by dfoll** [comment]
We have decided that we will be removing the Python Package for the October release

**Comment by lfunkhouser** [comment]
Retest on 2.2, 2.3, 2.4

**Comment by dfoll** [comment]
For the October release we have now decided to leave the Python package in the .zip file. Messaging on the Get started page is good. We will be adding a .readme file to the install warning the user not to install it on 2.4.

**Comment by lfunkhouser** [comment]
PDF build 341 verified doc updates

**Comment by lfunkhouser** [comment]
Tested also on Pro 2.5.
