### ISSUE TITLE
Update add-in version

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-desktop-addins#120]
Update versions based on version in table, https://github.com/Esri/military-tools-desktop-addins/wiki/Military-Tools-Releases-and-Versions

- [x] Update version table
- [x] Update MT add-in to 3.6
- [x] Update the conda package name to version 3.6
- [x] Update CC add-in version
- [x] Update DD add-in version
- [x] Update Vis add-in version
- [x] Update MSE add-in version

Build the addins

- [x] MT add-in to 3.6
- [x] The conda package name to version 3.6
- [x] CC add-in version
- [x] DD add-in version
- [x] Vis add-in version
- [x] MSE add-in version

**Comment by lfunkhouser** [comment]
Wiki updated with version numbers, https://github.com/Esri/military-tools-desktop-addins/wiki/Military-Tools-Releases-and-Versions.

**Comment by csmoore** [comment]
I'll update the versions in the [jenkins addins-info](https://github.com/ArcGIS/solutions-defense/blob/dev/Jenkins/add-ins-info.json) and [conda setup file](https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/dev/tools/setup.py) now

**Comment by csmoore** [comment]
Version numbers updated in PRs:

https://github.com/ArcGIS/solutions-defense/pull/1010
https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/422

**Comment by dfoll** [comment]
### Confirm [Version numbers](https://github.com/Esri/military-tools-desktop-addins/wiki/Military-Tools-Releases-and-Versions)
- [ ] MT add-in -- 3.6
- [ ] The conda package -- 3.6
- [ ] CC add-in version -- AM 2.6.1/Pro 4.4.1
- [ ] DD add-in version -- AM 2.4.1/Pro 4.2.1
- [ ] Vis add-in version -- AM 4.0.4/Pro 4.2.4
- [ ] MSE add-in version -- 4.4.0
