### ISSUE TITLE
Update Resource Versions For Release

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-desktop-addins#16]
Update the resources (ex: version and dates in Daml and addinx files) for Release:

Proposed Versions:

Version: 1.1  

| Repo Name | Version/Release | 
|--- | --- | 
| coordinate-conversion-addin-dotnet | 2.1.0 | 
| distance-direction-addin-dotnet | 2.1.0 |
| military-symbol-editor-addin-wpf | 2.1.0 | 
| military-tools-geoprocessing-toolbox `*`  | 1.1.0 |
| military-tools-desktop-addins | 1.1.0 | 
| solutions-webappbuilder-widgets `*` | 2.1.0 |
| visibility-addin-dotnet | 2.1.0 |

`*` - no version resources to update

~~Update wiki after release:~~ https://github.com/Esri/military-tools-desktop-addins/wiki/Releases

Update: a **draft** release for this is on wiki here: https://github.com/Esri/military-tools-desktop-addins/wiki/Releases#version-11--june-2017

**Comment by csmoore** [comment]
Pull Requests with version updates made:

https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/363
https://github.com/Esri/distance-direction-addin-dotnet/pull/395
https://github.com/Esri/military-symbol-editor-addin-wpf/pull/160
https://github.com/Esri/visibility-addin-dotnet/pull/200
https://github.com/Esri/military-tools-desktop-addins/pull/17

**Comment by ACueva** [comment]
@csmoore Changes have been merged.

**Comment by csmoore** [comment]
Not sure if this needs PE verified, just close if not

**Draft** release matrix/table is here: https://github.com/Esri/military-tools-desktop-addins/wiki/Releases#version-11--june-2017
