### ISSUE TITLE
Add "Dark theme" Support

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-desktop-addins#2]
Switching **ArcGIS Pro 1.4+** to Dark Theme in options cause visibility issues with some UI elements:

Issue to capture all dark theme issues in ArcGIS Pro 1.4+ - add a line/check box for any issues encountered (starting with issue list from previous repo):

**Military Tools for ArcGIS Toolbar**
- [x]  None

**Coordinate Conversion**
- [x]  Dark and White Backgrounds mixed in Text/Combo Boxes (See: **2:** Below)

**Distance and Direction**  
- [x] Label Text that is hard to read (See **1:** Below)
- [x]  Dark and White Backgrounds mixed in Text/Combo Boxes (See: **2:** Below)

**Visibility** 
- [ ] Label Text that is hard to read (See **1:** Below)

**Military Symbol Editor**
- [x] Tags

---

Esri UI Design guidance on this is at: https://blogs.esri.com/esri/arcgis/2017/01/30/arcgis-pro-ui-styling-with-the-pro-sdk/

---

Examples:

**1:**
![image](https://cloud.githubusercontent.com/assets/13024357/21826579/e7ff05b2-d73c-11e6-9d4e-76366c82ab0f.png)

**2:**
There are input text boxes and non-input text boxes that have both white and black backgrounds.
![image](https://cloud.githubusercontent.com/assets/5016557/21825113/38d991d8-d737-11e6-9766-e4c20b13ab71.png)

![image](https://cloud.githubusercontent.com/assets/5016557/21825213/a94f5c04-d737-11e6-8bd9-da8bbae05ea2.png)

**Comment by csmoore** [comment]
I think addressing the remaining Dark Theme issues for Visibility, Distance and Direction, and Coordinate Conversion (which share the controls between ArcMap and Pro) is going to involve a larger effort and following this example: 

https://github.com/Esri/arcgis-pro-sdk/wiki/ProGuide-Applying-Custom-Styles 
https://github.com/Esri/arcgis-pro-sdk-community-samples/tree/master/Framework/CustomStyling

Which is fairly straightforward and doable, but will be time consuming to go through every UI element so  I'm just not sure we will have the time for this release/spint, but let me know what you think - @nfeuerstein @kgonzago @dfoll

**Comment by nfeuerstein** [comment]
How much time are we talking about? It was communicated as part of the plan for this release and there is no technical limitation, correct?

**Comment by csmoore** [comment]
No technical limitation, just a change in understanding and effort since it is now understood that this will involve developing a theme and changing every element of the UI. I would probably allow at least a week to do and test.

Speaking just for myself, when I looked at this issue, I thought it was just tweaking a few UI elements and not a whole UI theme recode, but looking at some of these issues (ex: https://github.com/Esri/visibility-addin-dotnet/issues/198), implementing a theme seems like the only way to get to this level of perfection (i.e. swap white/black labels).

**Comment by topowright** [comment]
@nfeuerstein @lfunkhouser I have documented that Military Tools doesn't fully support Dark Theme and i am going to move this topic to Version after next. If that is not what is supposed to happen I misunderstood you today.

**Comment by topowright** [comment]
We need to break each of these changes into smaller issues. There is a chance that we have already done this.

**Comment by topowright** [comment]
This issue is being closed because it does not identify a fix that needs to be done for the Military Tools Repo. 

This is the issue that needs to be addressed. 
https://github.com/Esri/distance-direction-addin-dotnet/issues/482
