### ISSUE TITLE
Update version of add-in to 2.0

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-desktop-addins#21]
Build 1615
Military Tools Add-In version needs to be updated to 2.0 before it is released.

**Comment by dfoll** [comment]
This is what everything is labeled as at build 1618
- [ ] CC Pro 3.0
- [ ] DD Pro 3.0
- [ ] MSE Pro 2.0
- [ ] Viz Pro 3.0
- [ ] CC Map 2.1.1
- [ ] DD Map 2.1 
- [ ] Viz Map 2.1
- [ ] MTA Pro 2.0 
- [ ] MTA Map 2.0

**Comment by csmoore** [comment]
@pHill5136 made some version updates after this build - [ex](https://github.com/Esri/military-symbol-editor-addin-wpf/pull/192)

Do we have a draft table of what these versions should be for this July release:
Ex: https://github.com/Esri/military-tools-desktop-addins/wiki/Releases

**Comment by csmoore** [comment]
The wiki has been updated with a draft release based on the discussion above at - please have a look to make sure there is agreement on these:

https://github.com/Esri/military-tools-desktop-addins/wiki/Releases#version-20--july-2017-draft

**Comment by lfunkhouser** [comment]
Tested add-in versions in build 1624. Those are verified as fixed.

- Single Add-in for ArcGIS Pro is version 2.0 for Military Tools 2.0 release.
- Single Add-in for ArcMap is version 2.0 for Military Tools 2.0 release.
- Component add-ins for ArcMap are version 2.1.1 - verified as fixed since the ArcMap add-ins had bug fixes only
- Component add-ins for ArcGIS Pro are version 3.0 - verified as fixed since these support ArcGIS Pro 2.0 and was a breaking change

@csmoore The only change in the referenced wiki would be the Military Tools Geoprocessing Toolbox release would be 1.2 - added functionality with the new tool.

**Comment by csmoore** [comment]
@lfunkhouser - wiki updated to reflect Military Tools Geoprocessing Toolbox change: https://github.com/Esri/military-tools-desktop-addins/wiki/Releases#version-20--july-2017-draft

**Comment by lfunkhouser** [comment]
@csmoore This release also includes the ArcGIS Pro add-ins for ArcGIS Pro 1.4-1.4.1. I've updated the wiki, adding the repo/link to the v2.1 branches of the repos. Can you take a look and review?

**Comment by lfunkhouser** [comment]
Closing. Add-ins are updated and released. Release wiki is updated.
