### ISSUE TITLE
Dependency renamed, breaks build

### ISSUE THREAD

**Issue by ACueva** [Esri/military-tools-desktop-addins#27]
https://github.com/Esri/visibility-addin-dotnet/pull/224

Point build to utilize new folder structure.

**Comment by csmoore** [comment]
@ACueva - Should be good to verify with merge of #28

**Comment by ACueva** [comment]
Verified.  Updated the Jenkins build to reflect these changes.  For future work, if you were to link to the lines of code that affect the build location, I would appreciate it.  It would make it easier to track where I need to make these modifications. Thanks.

**Comment by csmoore** [comment]
@ACueva - sorry I bamboozled the build fren 🐶
