### ISSUE TITLE
When normal.mxt gets saved with a Military Tools window open it causes a crash when double-clicking any other saved .mxd

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-desktop-addins#33]
_From @dfoll on September 12, 2017 21:53_

When normal.mxt gets saved with a Military Tools window open it causes a crash when double-clicking any other saved .mxd to open.

1. Delete normal.mxt (located in C:\Users\xxxxXXXX\AppData\Roaming\ESRI\Desktop10.3\ArcMap\Templates  with a typical installation) 
2. Open ArcMap. Add a basemap. Save as "noMT.mxd". Close.
3. Close ArcMap. Double-click "noMT.mxd" and it opens. "noMXT.mxd" opens.
4. Add the Military Tools toolbar. Save as "MT_toolbar.mxd" and close.
5. Double-click "MT_toolbar.mxd" and it opens. 
6. Save as "MT_toolbar_CCwindow.mxd", and close.
7. Double-click "MT_toolbar_CCwindow.mxd", and ArcMap crashes when it tries to open the document.
8. Open ArcMap and browse to "MT_toolbar_CCwindow.mxd" and open it, it opens fine. 
9. Close "MT_toolbar_CCwindow.mxd" without saving.
10. Delete normal.mxt.
11. Double-click "MT_toolbar_CCwindow.mxd" and it opens (without the CC window or MT toolbar, because you deleted normal.mxt) 
12. Add the Military Tools toolbar and open the Coordinate Conversion window.
13.  Save as "MT_toolbar_CCwindow.mxd" and close.
14. Double-click "MT_toolbar_CCwindow.mxd".  ArcMap closes when trying to open.
15. Open ArcMap and browse to "MT_toolbar_CCwindow.mxd" and open it, it opens fine.
16. Close the Coordinate Conversion window, and save as "MT_toolbar_CCwindow.mxd"
17. Double-click "MT_toolbar_CCwindow.mxd" to open, it opens fine.
18. Open the Distance and Direction window. Save as "MT_toolbar_DDwindow.mxd", and close.
20. Double click "MT_toolbar_DDwindow.mxd" (or any of the other .mxds created in previous steps) to open, and it crashes ArcMap.
21. Open ArcMap and browse to "MT_toolbar_DDwindow.mxd", it opens.
22. Close the Distance and Direction window and open the Visibility window, and save as "MT_toolbar_Vizwindow.mxd" and close.
23. Try double-click to open "MT_toolbar_Vizwindow.mxd" (or any of the other .mxds created in previous steps), ArcMap crashes.
24. Delete normal.mxt
25. Open any of the .mxds previously created (5 at this point) and any of them open, (without a MT window open or the Military Tools toolbar, because you deleted normal.mxt)

repro steps are from 10.3.1 

_Copied from original issue: ArcGIS/solutions-defense#424_

**Comment by lfunkhouser** [comment]
_From @dfoll on September 12, 2017 21:59_

original Esri Case #01968472

**Comment by lfunkhouser** [comment]
_From @BobBooth on September 26, 2017 18:38_

I can confirm that this issue also exists for 10.6

**Comment by lfunkhouser** [comment]
_From @BobBooth on September 27, 2017 15:8_

Also, for what it is worth, it is the Coordinate Conversion part that seems to be causing the crash. I can open maps with the Distance and Direction stand alone add-in installed and the window open just fine, but the same map, if I open CC will crash next time I open it.

**Comment by lfunkhouser** [comment]
_From @csmoore on November 14, 2017 18:58_

This is a serious issue and seems to be easily reproducible just by re-running ArcMap when the coordinate conversion (CC) dock window was previously opened. 

Technical details of problem:
The issue was that the CC dockwindow expects the map to be open and available to subscribe to ActiveView events when the dock window is created - and in this case - the CC doc window is opened before the map.  So need to change the code to pick a better time to subscribe to ActiveView events.

Addressed in https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/453

**Comment by lfunkhouser** [comment]
_From @csmoore on November 29, 2017 14:42_

Ready to verify 

Combined addin (from Jenkins build) is at: 
`{server}\Development\Commercial\MilitaryToolsForArcGIS\11-29-2017_1644` - 
MilitaryToolsforArcMap.esriAddIn

ArcMap stand alone CC Addin:
`{server}\Development\Commercial\DefenseSolutions\11-29-2017_1644\ArcMap\Addins\CoordinateConversion` - CoordinateConversion.esriAddin

**Comment by lfunkhouser** [comment]
_From @ACueva on November 29, 2017 22:2_

@csmoore Hate to be the bearer of bad news.  Still not fixed.  I'm able to get it to crash if I do the following:

Open a blank ArcMap.  Make sure you have the latest addin installed.
Add an ArcGIS online basemap.
Open the Coordinate Conversion window pane.
Save the MXD.
Close ArcMap.

Re-open the MXD you just saved.
I was able to get ArcMap to crash at this point.

Tested on ArcMap 10.5.1.

**Comment by lfunkhouser** [comment]
_From @csmoore on November 30, 2017 15:59_

@ACueva - I was able to repro this same issue under this unique condition: addin compiled under an earlier version is run on 10.5.1+(I used 10.6). 

Added additional code in PR: https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/456 to hopefully fully address this now. Will kick off new build once merged.

**Comment by lfunkhouser** [comment]
_From @ACueva on November 30, 2017 16:36_

@csmoore I've reviewed/merged your changes.  I've also kicked off a new build.

**Comment by lfunkhouser** [comment]
_From @topowright on November 30, 2017 17:36_

Can we close this issue?

**Comment by lfunkhouser** [comment]
_From @ACueva on November 30, 2017 22:41_

@csmoore Still crashing with 10.5.1.  Let me know if you'd like to screen share:

Steps to repro:
1. uninstall previous version of Add-in.
2. open up ArcMap, make sure add-in is not present.
3. install latest version of add-in.
4. Open ArcMap and add a basemap.
5. Make sure the Coordinate Conversion window pane is open.
6. Save the mxd.
7. Close ArcMap.
8. Re-open the new mxd by double clicking on it.

I can get ArcMap to crash consistently by following these steps.

**Comment by lfunkhouser** [comment]
_From @csmoore on December 1, 2017 12:19_

@ACueva - thanks for testing - since I can't repro now - if we can get together and get your crash dump with a debug version.

**Comment by lfunkhouser** [comment]
_From @csmoore on December 4, 2017 17:39_

I can repro this and see the issue with the MilitaryTools toolbar addin (MilitaryToolsforArcMap.esriAddIn - this should be fixed in the single CC addin now though) - I didn't realize similar code/issue also existed with MilitaryTools toolbar addin - still working on fix

**Comment by lfunkhouser** [comment]
_From @ACueva on December 4, 2017 17:45_

I will verify this issue is no longer occurring on the single add-in.

**Comment by lfunkhouser** [comment]
_From @ACueva on December 4, 2017 23:58_

Verified this is issue is no longer occurring on the Coordinate Conversion single add-in.

**Comment by lfunkhouser** [comment]
_From @csmoore on December 5, 2017 15:55_

I have a workaround for this issue started at 
https://github.com/Esri/coordinate-conversion-addin-dotnet/tree/csm/%23427-crash-MT-toolbar 
https://github.com/Esri/military-tools-desktop-addins/tree/csm/%23424-crash-MT-toolbar

However, while testing, I also see this issue in the other 2 addins (D&D & Viz - crash if DockPanel open on startup - slightly different in that you need to select a tool to get crash to happen) so will fix there as well before PR/test.

**Comment by lfunkhouser** [comment]
_From @topowright on December 5, 2017 16:36_

@csmoore good catch. We will need to open issues for each of those add-ins to allow us to track the updates.

**Comment by csmoore** [comment]
This should be ready to verify from: 

`Development\Commercial\DefenseSolutions\12-05-2017_1646\ArcMap\Addins\CoordinateConversion'
`Development`

`Development\Commercial\MilitaryToolsForArcGIS\12-05-2017_1646\ArcMap\Addins`

Note: 

1. this is an ArcMap-only issue that seems to occur most often on more recent versions (10.5+)
2. This same issue occurs in D&D and Viz addins - but has not been fixed yet:
    a. https://github.com/Esri/distance-direction-addin-dotnet/issues/471
    b. https://github.com/Esri/visibility-addin-dotnet/issues/247

**Comment by csmoore** [comment]
Ready to QA with all addins from `Development\Commercial\MilitaryToolsForArcGIS\12-06-2017_1649`

**Comment by topowright** [comment]
Verified this on 10.6 version: 8315
