### ISSUE TITLE
Build number captured for Military Tools for ArcGIS similar to CC  in ArcGIS Pro

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-desktop-addins#37]
### Expected Behavior

Military Tools for ArcGIS should have a build number populated based on the build number from Jenkins.
**This is for ArcGIS Pro only not for ArcMap for now.** 
The code on how we did this for Coordinate Conversion in ArcGIS  Pro is the samething we want to do for this issue: 
https://github.com/Esri/coordinate-conversion-addin-dotnet/commit/22fad093d63e196d51497ed57dc1bf8b44097c98#diff-d9358db34019268f8ca62c22b2ef1c48R222

### Current Behavior

Currently we do not have any way to identify what build is installed on ArcGIS Pro

**Comment by topowright** [comment]
working on making sure that our build process is ready for this capability

**Comment by topowright** [comment]
Military Tools for ArcGIS is building with build numbers and ready for this feature enhancement when we are able to get to it.

**Comment by dfoll** [comment]
where is this build number shown?

**Comment by topowright** [comment]
Buillt and tested on @kgonzago  branch and now we have this: 
![image](https://user-images.githubusercontent.com/5488313/34633765-26aa5a8e-f233-11e7-9c00-ee55f76d0341.png)

**Comment by topowright** [comment]
It also shows up in this location of ArcGIS Pro as well: 
![image](https://user-images.githubusercontent.com/5488313/34633917-3893f9ca-f234-11e7-84a2-8375071a1f27.png)

**Comment by lfunkhouser** [comment]
We need an internal build number. Incrementing the add-in release version was not the intent. The version on the add-in that we release as version 3.0 will need to state 3.0, not 3.0.x. Is this do-able?

**Comment by kgonzago** [comment]
Which UI are you referring to? The UI when installing the add-in or the UI of the Add-in manager in Pro?

**Comment by topowright** [comment]
Are we one number off based on this capture from ArcMap? 

![image](https://user-images.githubusercontent.com/5488313/34682196-05af614a-f453-11e7-93e5-247af7db8aca.png)

**Comment by topowright** [comment]
@kgonzago is going to make this match the way that we do it for ArcMap.
