### ISSUE TITLE
Understanding why we have to build Military Tools on 2.1

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-desktop-addins#39]
It has been decided that we are going to create a non backwards compatible version of Military Tools starting at ArcGIS Pro 2.1. 
### Questions
What features or bugs is making this inevitable? 

The only feature that I understand that has kept us to continue building on ArcGIS Pro 2.0 is: 
https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/460

**Comment by topowright** [comment]
@csmoore please provide intimate details to allow us to understand our direction forward based on the changes in the technology.

**Comment by csmoore** [comment]
@topowright - that issue mentioned - https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/460 - should have the details of what is going on, but let me know if something needs added (I did add a new comment at 
https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/460#issuecomment-355941244 )

**Comment by topowright** [comment]
This issue can now be closed.
