### ISSUE TITLE
This issue has been opened to transfer labels to another GitHub repo

### ISSUE THREAD

**Issue by ACueva** [Esri/military-tools-desktop-addins#4]
_From @lfunkhouser on January 5, 2017 22:58_

_From @lfunkhouser on January 5, 2017 22:57_

_Copied from original issue: Esri/coordinate-conversion-addin-dotnet#224_

_Copied from original issue: ArcGIS/military-tools-arcmap-single-add-in_RETIRED#4_

**Comment by ACueva** [comment]
_From @lfunkhouser on January 5, 2017 23:4_

This issue was moved to ArcGIS/military-tools-pro-single-add-in#7

**Comment by csmoore** [comment]
Thanks @ACueva
