### ISSUE TITLE
Military Tools hiding the add-in tab

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-desktop-addins#41]
Currently I think our product hides the add-in tab
### Expected Behavior

If I have other add-ins that I want to work with along with Military Tools Installed I do not have access to the Add-in ribbon
### Current Behavior

I think we are hiding the add in ribbon in Military Tools
### Steps to Reproduce (for bugs)

install a add in 
Install Military tools and then try to access the other add in
### Your Environment

* Addin Version used: 
* Environment name and version (e.g. ArcMap 10.3, Pro 1.4):
* Operating System and version (desktop or mobile):
* Link to your project/test data (if applicable):

**Comment by lfunkhouser** [comment]
@topowright What add-in did you install with MT? Provide screenshots to clarify this issue.

**Comment by topowright** [comment]
I have now tested this with a newer version of Military Tools and it is no longer an issue.
