### ISSUE TITLE
Update the Target Version for 3.0 reflecting ArcGIS Pro 2.1

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-desktop-addins#44]
**DEV**
- [x] Change the target version to ArcGIS Pro 2.1 for Each Pro Addin
    - [x] Toolbar
    - [x] CC - https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/479
    - [x] DD (already done)
    - [x] Viz - https://github.com/Esri/visibility-addin-dotnet/issues/267
    - [x] MSE - https://github.com/Esri/military-symbol-editor-addin-wpf/issues/215
 
**CHECKLIST**
- [x] Add statement to checklist to identify the target version is correct 
Note: rather than list a specific version step can be to just cross check against [release table for releasse](https://github.com/Esri/military-tools-desktop-addins/wiki/Military-Tools-Releases-and-Versions)

ISSUE:

Currently our 3.0 built add-in shows version 2.0 should be 2.1
![image](https://user-images.githubusercontent.com/5488313/36286531-09f4344e-1265-11e8-8f57-8f14d2e7cb8d.png)

**Comment by topowright** [comment]
**DEV**
- [ ] Change the target version to ArcGIS Pro 2.1

**CHECKLIST**
- [ ] Add statement to checklist to identify the target version is correct

**Comment by csmoore** [comment]
Addressed for toolbar and all addins in PRs:

 Toolbar - #48
 CC -https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/483 
 DD (already done)
 Viz - https://github.com/Esri/visibility-addin-dotnet/pull/274
 MSE - https://github.com/Esri/military-symbol-editor-addin-wpf/pull/216

Ready for QA/QC after merge

**Comment by ACueva** [comment]
Removing G-QC Verify as I've verified the version is correct for all the following addins:

- [ ] CC  
- [ ] DD 
- [ ] Viz
- [ ] MSE

I've also added the following wording to the checklist tests:
```
Version (Verify this is correct version based off this [matrix](https://github.com/Esri/military-tools-desktop-addins/wiki/Military-Tools-Releases-and-Versions))
```
- [ ] CC  
- [ ] DD 
- [ ] Viz
- [ ] MSE
https://github.com/ArcGIS/solutions-defense-test-catalog/commit/da632354283fc6b44490c56c898116cd5060d721

**Comment by ACueva** [comment]
Moving back to the backlog for the Checklist verification task.

**Comment by dfoll** [comment]
![image](https://user-images.githubusercontent.com/5322669/37115804-14d7e6ac-2201-11e8-9db9-3b35bad2371f.png)
![image](https://user-images.githubusercontent.com/5322669/37115818-24a8da5a-2201-11e8-8149-f5ba6cf0f5cb.png)
![image](https://user-images.githubusercontent.com/5322669/37115828-3058cc52-2201-11e8-81b3-1a210211f3f7.png)
![image](https://user-images.githubusercontent.com/5322669/37115842-3f24e28e-2201-11e8-960d-cf48241ee5da.png)
![image](https://user-images.githubusercontent.com/5322669/37115941-89faff3c-2201-11e8-96db-da727194b145.png)

-verified/updated checklist tests
