### ISSUE TITLE
ArcMap Addin Build Error on ArcMap 10.6

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-desktop-addins#45]
Attempting to build ArcMap addins on ArcMap/ArcObjects SDK 10.6 results in error: *"Unable to create .esriAddin; missing ESRI ArcGIS Add-in SDK component(s)."*

Ex:
`ArcMapAddinDistanceAndDirection\ArcMapAddinDistanceAndDirection.csproj(241,5): warning : Unable to create .esriAddin; missing ESRI ArcGIS Add-in SDK component(s).`

**Reason:**

The project is looking for the original name for this file which was `ESRI.ArcGIS.AddIns.11.targets` and it has been changed (again) to `ESRI.ArcGIS.AddIns.targets`  

Note: this is similar (but reversed) to the problem building on 10.3 discussed here: https://community.esri.com/thread/118989)

**Workaround:**

To workaround this problem, go to the `%MSBuildExtensionsPath%` folder:

VS2017 : `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild`
VS2015:  `C:\Program Files (x86)\MSBuild\Esri`

Copy `ESRI.ArcGIS.AddIns.targets` -> `ESRI.ArcGIS.AddIns.11.targets`

@kgonzago - FYI

**Comment by ACueva** [comment]
I remember having to implement this work-around on our original build environment.  Ideally this would be best handled on the code side, but if needed we can modify the build environment as needed.

**Comment by csmoore** [comment]
We have 2 main options for addressing this issue:

1. Move the build to ArcMap 10.4+ (which looks for `ESRI.ArcGIS.AddIns.targets`) if possible and 10.3 no longer a requirement.

-or- 

2. If 10.3 is still a requirement, add logic to the VS project to try/look for both versions of the file: 

    1. ESRI.ArcGIS.AddIns.targets
    2. ESRI.ArcGIS.AddIns.11.targets

**Comment by ACueva** [comment]
@csmoore How big of an effort is it for Part 2 of your suggested options?

**Comment by csmoore** [comment]
@ACueva - probably just a few hours to implement in MSBuild(.vsproj) and test on 10.3 + 10.6

**Comment by topowright** [comment]
This is not an issue as of now, but we need to think about how do we support mutiple builds of the product.
