### ISSUE TITLE
Support for ArcMap 10.6

### ISSUE THREAD

**Issue by sindizzy** [Esri/military-tools-desktop-addins#46]
Addin Version used:  Feb 2017 release
Environment name and version: ArcMap 10.5.1 and 10.6
Windows 10 Enterprise x86 and x64 Desktop

We are at 10.1 currently and the only thing holding us back was the use of the Military Analyst extension. In our custom extension I have worked for a year or two to replace all MA API with core ArcGIS functionality. That part is complete but the users also quite heavily use the MA Toolbar. Mainly to draw geodesic lines and geoellipses.

I see that the Military Tools add-in has most if not all the functions from Military Analyst. I am overwhelmingly thankful for the work that has gone into this add-in. It will save me tons of time. Thanks!!! Now on to my question...does this release support ArcMap 10.6? We can upgrade to 10.5 but if the MT add-in supports 10.6 then we will make that jump.

Rgds
~AGP

**Comment by csmoore** [comment]
@sindizzy - although the [online help page](http://solutions.arcgis.com/defense/help/military-tools/) won't be officially updated until April, any ArcMap version [after 10.3.1 should work](https://github.com/Esri/military-tools-desktop-addins#build-requirements)

@ACueva @dfoll @topowright @lfunkhouser FYI

**Comment by lfunkhouser** [comment]
Military Tools for ArcGIS is officially supported on 10.6. It is also certified and supports 10.6.1 when it is available. In addition, this June 2018 release of Military Tools supports Pro 2.1 and Pro 2.2.

Closing this issue.
