### ISSUE TITLE
ArcGIS License Level for certain functions

### ISSUE THREAD

**Issue by sindizzy** [Esri/military-tools-desktop-addins#47]
Feb 2017 Release: Just absolutely love this add-in. I have been testing it on ArcMap 10.6 and so far so good. One thing, however, that I did notice is the requirements on the home page do not specify what license level of ArcMap is required. I think for the most part Basic is supported. But the Toolbox function "Find Local Peaks" requires a call to FeatureToPoint_management which according to the ESRI help

Licensing information
ArcGIS Desktop Basic: No
ArcGIS Desktop Standard: No
ArcGIS Desktop Advanced: Yes

The error says the appropriate license was not found and I checked to make sure that Spatial Analyst and 3D Analyst were checked. But it turns out it's the core ArcGIS License Level that caused this error.

Either way this tool is awesome! I will continue my testing.

**Comment by lfunkhouser** [comment]
Thank you @sindizzy for your feedback. We plan to add the licensing requirements to the website and to the distributed documentation with the product in the next release.

**Comment by sindizzy** [comment]
Many thanks. I am going to download the source and see if I can make any modifications ans suggestions.

**Comment by lfunkhouser** [comment]
Verified. The licence matrix is included in the documentation in the June 2018 release for Military Tools for ArcGIS 3.0.

http://solutions.arcgis.com/defense/help/military-tools/resources/system-requirements.htm
