### ISSUE TITLE
Update Addin Dates for next release

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-desktop-addins#49]
Similar to Issue #44 (update target version) and PR #38 - we should update the dates for the next release (i.e. 4/XX/2018).

**DEV**

- [x] Modify the Visual Studio Project file to set the addin date to %BUILD_DATE% environment variable if it is set (by Jenkins for instance) - otherwise use the system date.

___

**QC/ CHECKLIST**

- [x] Check the release date for each:
- [x] ArcMap Addin
   - [x] Toolbar
    - [x] CC 
    - [x] DD
    - [x] Viz 
- [x] Pro Addin
   - [x] Toolbar
    - [x] CC 
    - [x] DD
    - [x] Viz 
    - [x] MSE
 
- [x] Add statement to checklist to identify the addin date is correct 
Note: rather than list a specific date, the step can be to just cross check against [release table for release](https://github.com/Esri/military-tools-desktop-addins/wiki/Military-Tools-Releases-and-Versions)

**Comment by csmoore** [comment]
If you do ever decide to automate updating the addin date with build - here are the sample changes:

1. Addin Project Changes (similar to changes done for BUILD_NUMBER)
Diff: https://github.com/Esri/visibility-addin-dotnet/compare/csm/%2349-update-date-in-daml
Branch: https://github.com/Esri/visibility-addin-dotnet/tree/csm/%2349-update-date-in-daml 

2. Jenkins would then need to set a variable "BUILD_DATE" prior to build (like it does for BUILD_NUMBER)

@topowright @lfunkhouser ( also it was mentioned you discussed with @chris-fox )

**Comment by csmoore** [comment]
Just verifying the date you want to manually set for the addins is: **6/26/2018** 

@lfunkhouser @topowright @dfoll @ACueva

**Comment by dfoll** [comment]
to my knowledge it is still the 26th, i can't find my link right now to look at the actual release page for agol

**Comment by lfunkhouser** [comment]
@csmoore Yes, that is currently the accurate release date and the one that should be used for the add-ins.

**Comment by csmoore** [comment]
For the build date - we decided to go with automating this, since it was about the same level of effort as manually updating. Here is how the build date should work on Studio project build: 

If a BUILD_DATE environment variable is set (by Jenkins for instance) - it just uses that, otherwise it uses the system date.

Updated in PRs:

Date-only change needed:
https://github.com/Esri/military-symbol-editor-addin-wpf/pull/240
https://github.com/Esri/distance-direction-addin-dotnet/pull/606

Date and ArcMap Build Number change needed - also covered by #50 (Note: affected same file/section so included in same PR):
https://github.com/Esri/military-tools-desktop-addins/pull/58
https://github.com/Esri/visibility-addin-dotnet/pull/282
https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/500

**Comment by topowright** [comment]
Currently we need to find a way to have separate build numbers for ArcMap and ArcGIS Pro.

**Comment by topowright** [comment]
Reverting the PR's now so that they can be redone to have all build numbers and version numbers correct.

**Comment by csmoore** [comment]
@topowright @ACueva - the project files just use the environment variables:

BUILD_MAJOR, BUILD_MINOR, ,BUILD_PATCH, BUILD_NUMBER

Would it be possible to set those environment variables to different values prior to kicking off the ArcMap projects build?

**Comment by topowright** [comment]
This was done by @csmoore last sprint and now we understand how to use this work and the build number work that he did. This can now be moved to done.
