### ISSUE TITLE
Released software links are pointing to dev branch not master

### ISSUE THREAD

**Issue by adgiles** [Esri/military-tools-desktop-addins#5]
If you follow any of the links on the release page here:

https://github.com/Esri/military-tools-desktop-addins/wiki/Releases#version-10

You are directed to the dev branch not the master branch which contains the released version.

This could be confusing for the user as they may accidentally end up downloading a version that is incomplete as work is still in progress or not tested. 

I think this link should point to the master branch.

**Comment by csmoore** [comment]
It was meant to take you to the repo, where you then are meant to get the actual release: https://github.com/Esri/solutions-webappbuilder-widgets/releases 

But we can add a column that links to the actual release ex: -https://github.com/Esri/solutions-webappbuilder-widgets/releases/tag/v2.0-for-mt-1.0 if that will help.

But I think in general these wiki's are not meant to be tightly controlled so feel free to edit and improve these at will (maybe just add an edit/commit comment when you do)

**Comment by csmoore** [comment]
@adgiles Thanks for the suggestion - I went ahead and added links to the actual releases to the [table](https://github.com/Esri/military-tools-desktop-addins/wiki/Releases#version-10) - please close this issue if that works.

**Comment by adgiles** [comment]
I was more on about the repo link going to dev not master

**Comment by csmoore** [comment]
I did consider that, but since Master itself will change from release to release, I figured it was probably better to link to the actual release.  Ex linking the 1.0 release to Master will be incorrect once master moves to 2.0. Hope that helps.

**Comment by adgiles** [comment]
Fair enough, but I think there needs to be a warning note visible to the user that the link points to the dev branch and they will need to change to the latest release before download, otherwise I can see that users will follow the link to the repo, go straight to download or clone and have the dev branch not the release branch.

**Comment by csmoore** [comment]
OK, it sounds like a more general issue then - not just with this table, but for anyone who arrives at one of these repos from anywhere.  

It sounds like you may not want the **default branch** set to "dev" (i.e. Development, not stable/fully tested), but changed back to "master" on these repos.  It is a bit unusual to have the default branch set to dev - but that is the current convention used with these - just check with the admins for these repos if you think this needs revisited.

**Comment by adgiles** [comment]
@nfeuerstein please advise which branch you would prefer to be the default

**Comment by elinz** [comment]
@adgiles @csmoore @nfeuerstein This is a good discussion to have not just for this repo, but for all our repos.

**Comment by kgonzago** [comment]
Technically, our customers should be navigated to the ```master``` branch since it is the latest _released_ version of our software. Given our repos have ```dev``` as the default branch, it makes it easier for developers to create a new PR and have that PR automatically perform a diff against ```dev```. I suggest we make ```master``` the default branch and have our developers make PRs against the ```dev``` branch. Once we are a go for release, we will then merge ```dev``` into ```master```.

Also, here's a good read on branching model: [GiHub Flow](http://scottchacon.com/2011/08/31/github-flow.html) and [Git Branching Model](http://nvie.com/posts/a-successful-git-branching-model/)

**Comment by lfunkhouser** [comment]
I agree with @kgonzago. Navigate customers to ```master```, the stable, released code. These links would be directed to that branch, i.e https://github.com/Esri/coordinate-conversion-addin-dotnet/tree/master.

**Comment by lfunkhouser** [comment]
Assigning to MT PEs to update the wiki.
@ACueva @dfoll @topowright @NatalieCampos

**Comment by dfoll** [comment]
@kgonzago @csmoore @adgiles @lfunkhouser   i have done the work, can someone confirm this is what you wanted?

**Comment by dfoll** [comment]
@adgiles  please confirm this is what you wanted and close if it is

**Comment by csmoore** [comment]
Closing - looks like table pointing to master
