### ISSUE TITLE
Update the addin version number for ArcMap addins

### ISSUE THREAD

**Issue by csmoore** [Esri/military-tools-desktop-addins#50]
We updated the **Pro Addins** versions/auto-version-setting process (ex: [here](https://github.com/Esri/military-tools-desktop-addins/pull/38), [here](https://github.com/Esri/distance-direction-addin-dotnet/pull/496)) and the ArcMap version/auto-version-setting process for **Distance and Direction** - https://github.com/Esri/distance-direction-addin-dotnet/issues/499 - but this same change is still needed for the remaining ArcMap addins

**DEV**

- [x] Change each project to get the version from Jenkins/build environment and update the esriaddinx file - like was done for D&D in https://github.com/Esri/distance-direction-addin-dotnet/pull/505/files to address https://github.com/Esri/distance-direction-addin-dotnet/issues/499

- [x] Change the project/version in the project file for each ArcMap Addin
    - [x] Toolbar
    - [x] CC 
    - [x] DD (Already done in https://github.com/Esri/distance-direction-addin-dotnet/issues/499 - https://github.com/Esri/distance-direction-addin-dotnet/pull/505/files
    - [x] Viz 
 
**DEV Jenkins**

- [ ] Make any necessary updates to set the version environment variables and test build

**CHECKLIST**

- [ ] Add statement to checklist to identify the addin version is correct 
Note: rather than list a specific version, the step can be to just cross check against [release table for release](https://github.com/Esri/military-tools-desktop-addins/wiki/Military-Tools-Releases-and-Versions)

**Comment by csmoore** [comment]
Updated in PRs:

https://github.com/Esri/military-tools-desktop-addins/pull/58
https://github.com/Esri/visibility-addin-dotnet/pull/282
https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/500

**Comment by topowright** [comment]
I have found a way to take advantage of the build numbers in our components for ArcMap and ArcGIS Pro. Updating the builds now.

**Comment by dfoll** [comment]
- [ ] CC
- [ ] DD
- [ ] MSE
- [ ] MT
- [ ] Vis
