### ISSUE TITLE
Map in Azimuthal_Equidistant results in odd behavior

### ISSUE THREAD

**Issue by sindizzy** [Esri/military-tools-desktop-addins#53]
### Expected Behavior
The Rings functionality should account for a map set in various coordinate systems. 

### Current Behavior
If a map is set to Azimuthal_Equidistant and the Distance and Direction>Rings function is used some odd behavior occurs. In non-interactive mode a center point is chosen in the middle of the USA. Number of Rings=5 with a distance between rings of 100NM. The function seems to do something as it zooms in to the area but no rings are drawn. However I zoom out and the rings are drawn but in a location far from the center point that was selected.

### Your Environment
* Addin Version used: June 2017 release
* Environment name and version: ArcMap 10.6
* Operating System and version: Windows 7 Enterprise x86

![image](https://user-images.githubusercontent.com/5298460/40927693-feac9fe2-67e4-11e8-9c56-a653316443f6.png)

**Comment by csmoore** [comment]
We have also run into this issue also since 10.4.1 - we logged an issue here against the map elements/map container: https://github.com/Esri/arcobjects-sdk-community-samples/issues/7 (this also references a bug ID)

**Comment by sindizzy** [comment]
Good news! The BUG-000114828 has been fixed at 10.7.1 https://downloads.esri.com/support/downloads/other_/1071-IssuesAddressedList-06212019.pdf
So from my testing it looks like this bug is present from 10.5.0 to 10.7.0 inclusive. After I reported the bug it took 16 months to fix.

**Comment by sindizzy** [comment]
Since MT uses graphics as its container in ArcMap then my suggestion would be to put a warning label if the user is using anything between 10.5.0 to 10.7.0 inclusive. For ArcGIS Pro the container is a geodb so bug is not applicable.

**Comment by csmoore** [comment]
@sindizzy - many thanks for testing+verifying+closing
