### ISSUE TITLE
Generate polygons for rings

### ISSUE THREAD

**Issue by sindizzy** [Esri/military-tools-desktop-addins#65]
As always thank you so much for a great product!
When we generate ellipses, circles, range rings I would vote for them to be created as a polygon rather than a polyline. Quite often I need to add a fill to the ellipse and as a polyline you can't do that. I believe the reason for this was so all geometry could be saved to one feature class. I think, as a user I would not mind one feature class for polylines and one feature class for polygons. Another reason I think polygons are a good idea is that post-processing like unionization of multiple polygons is possible.

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/distance-direction-addin-dotnet#625

**Comment by lfunkhouser** [comment]
Issue moved to the repo where the code/work for Distance and Direction functionality is managed.
