### ISSUE TITLE
Clear Graphics button not enabled after LLOS Military Tools - Visibility. Maybe not needed?

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-desktop-addins#7]
I ran the LLOS tool from the Military Tools in ArcGIS Pro 1.4.1. but can't clear the graphics
Multiple inputs and outputs.  Raster data in WGS 1984 UTM Zone 10N, set Map to have same coordinate system. Tool runs as expected. However, the Clear Graphics button does not become enabled.  I can delete the Observer Points and Target Points from the lists using right-click > Delete All, and add new observers and targets, and the process re-runs with expected results (old locations not included) but the old output hangs around on the display. Shouldn't I be able to clear them?

I see that the tool output is added as feature layers to the Contents (though Contents are hidden behind the Visibility tab, for me), so perhaps the workflow is to just remove them, or turn them off there... but in that case, why is there a "Clear Graphics" button on the tool in the first place? Does it do anything? Maybe should be removed.

ArcGIS Pro 1.4.1
Military Tools for ArcGIS 1.0
 installed on Pro1.4.1 using [server]\software\Esri\Released\ArcGISforDefense\MilitaryToolsforArcGIS1.0.zip

**Comment by csmoore** [comment]
There is an existing issue to remove this button: https://github.com/Esri/visibility-addin-dotnet/issues/154

**Comment by BobBooth** [comment]
Duplicate.
