### ISSUE TITLE
Visibility - RLOS and LLOS return "AddSurfaceInformation_3D" GP tool error on Pro 2.3

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-tools-desktop-addins#77]
### Expected Behavior
I've been trying to run Radial Line of Sight and Linear Line of Sight in Pro 2.3, but getting an error "AddSurfaceInformation_3D" when they try and run. 

### Current Behavior
I'm able to add inputs and click OK to start the process for both LLOS and RLOS. My elevation layer is in .tif format and projected, along with my map, in NAD 1983 StatePlane California IV Projected Coordinate System. I'm also able to reproduce with a variety of projected coordinate systems (including WGS 84 Web Mercator)

### Steps to Reproduce (for bugs)
1. Open a new project with a blank map
2. Add [this elevation layer](https://esri.box.com/s/jlz2nuizla5kp9zbjpjwsnbbf2bm6d36) to the map
3. Open the Visibility pane 
4. Enter parameters for LLOS or RLOS (I've tried with multiple observers/targets and single observer/target and get the same error)
5. Click OK to run, this is when I get this error: 

![image](https://user-images.githubusercontent.com/13024357/46428420-c3904080-c6f8-11e8-9f04-d18bd1d096ec.png)

### Your Environment

* Addin Version used: Military Tools 3.2
* Environment name and version (e.g. ArcMap 10.3, Pro 1.4): Pro 2.3 Build 14229 ICAP 2.0 beta build 580
* Operating System and version (desktop or mobile): windows 10

**Comment by Dbarnes1** [comment]
duplicate, closing

**Comment by dfoll** [comment]
@Dbarnes1 this looks like we have this captured [here](https://github.com/Esri/visibility-addin-dotnet/issues/304)
