### ISSUE TITLE
RLOS on image service fails with "calculation cancelled" message

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-desktop-addins#8]
I have added an image service of elevation data to my map.
(data at: http://navigator.state.or.us/arcgis/services  /Framework/Elevation_DEM_10)
I can run the Military Tools Add-In LLOS tool against it and it works (two points separated by 10,000 meters).
When I run the Military Tools Add-In RLOS against it (default values 1000 m distance, 2m height), I get a message box titled "Calculation cancelled" which says "Results not calculated. Check Input parameters and try again."
![image](https://cloud.githubusercontent.com/assets/3801392/23477649/a4cc8acc-fe8c-11e6-8cd7-bb14a594fb59.png)

### Expected Behavior
I would expect the tool to use the elevation data as it would a local layer. The LLOS tool does.

### Steps to Reproduce (for bugs)
Add image service of elevation data. (data at: http://navigator.state.or.us/arcgis/services  /Framework/Elevation_DEM_10)
Open LLOS tab. Add two points 10,000 meters apart. Accept defaults, click OK, get correct results.
Open RLOS tab. Add single point (in my case, near the midpoint of the previous two). Accept defaults. Click OK, get error message.

### Your Environment
ArcMap 10.4.1
Military Tools Add-in  build 1228
(03-01-2017_1228)

**Comment by kgonzago** [comment]
@csmoore can you look into this when convenient?

**Comment by csmoore** [comment]
I was able to repro this - the bug is [here](https://github.com/Esri/visibility-addin-dotnet/blob/dev/source/Visibility/ArcMapAddinVisibility/ViewModels/RLOSViewModel.cs#L987) (needs to also check for ImageServiceLayer)

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/visibility-addin-dotnet#184
