### ISSUE TITLE
Update the minor number in the version for the Military Tools desktop add-in

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-desktop-addins#80]
Current
The version of the add-in is 3.2.0.152

Expected
The version of the add-in should be updated to 3.3.0.<build>

**Comment by dfoll** [comment]
Looked at picking this up. Can someone else take a look. It looks to have already been completed to me. Included screenshots of all the places I could think to look. If there is sign off that this is all of it, we can move this to Done.
![image](https://user-images.githubusercontent.com/5322669/50919745-a95db100-1411-11e9-8836-0a715e549da4.png)

**Comment by BobBooth** [comment]
@dfoll - I'm seeing 3.3 in the doc and in the Pro and ArcMap Add-in installer pages.

**Comment by dfoll** [comment]
@BobBooth cool. I couldn't thing of anywhere else to look. @lfunkhouser did you have a specific place in mind you logged this against? or can we move to done?
