### ISSUE TITLE
Updating steps to add the python package 

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-desktop-addins#86]
The steps that it took to add a python package at ArcGIS Pro 2.2 have changed at ArcGIS Pro 2.3

### Expected Behavior

The steps need to be outlined for adding a python package at ArcGIS Pro 2.3 and previous versions. Previous versions allowed you to create a new environment via this dialog that is captured below. The add button only gives you an ability to add an existing environment.  The new concept has been removed or has been moved somewhere else. 

### Your Environment

![image](https://user-images.githubusercontent.com/5488313/49311714-c0b29180-f496-11e8-9d25-2636b61f2d50.png)

ArcGIS Pro 2.3 build: 15679

**Comment by dfoll** [comment]
this was worked on a while back. https://solutionsdev.arcgis.com/defense/help/military-tools/get-started/military-tools-for-arcgis-get-started.htm#ESRI_SECTION1_50EE8C523803469AA59344B1D8F70EA8

recommend reviewing quickly to make sure the steps are still accurate and no other changes have been made.

**Comment by dfoll** [comment]
trying to review now, and pro is taking an exceptionally long time to clone a new environment. not sure if something is wrong on my end, or this is the new behavior

**Comment by dfoll** [comment]
fix step 7 should say "clone" with a note that on 2.2 is says "save"

**Comment by dfoll** [comment]
This has been updated on DEV
 and in dev build 184
