### ISSUE TITLE
Military Tools GP tools from Conda package Radial Line of Sight and Linear Line of Sight lack input feature sets

### ISSUE THREAD

**Issue by BobBooth** [Esri/military-tools-desktop-addins#89]
With the latest build of Military Tools, when I install the GP tools using the Conda install package, two tools in the Visibility toolset lack feature sets for input observer points 
Radial Line of Sight
Linear Line of Sight (input observers missing, targets feature set is present)

![image](https://user-images.githubusercontent.com/3801392/50098529-21a5cd80-01ea-11e9-84dc-575be6cc0736.png)
![image](https://user-images.githubusercontent.com/3801392/50098943-f2dc2700-01ea-11e9-94e1-a77cea46523a.png)

RLOS and Range does have feature set.

This was fixed for the toolbox in the repo, I think the Conda package needs to be rebuilt with the latest version of the GP tools.

### Expected Behavior
Tools should have input observer points feature sets.

### Your Environment
Pro 2.3.0 Beta 2
Military Tools 12/14 build.

**Comment by lfunkhouser** [comment]
When rebuild conda package, update to version of MT and python in filename
militarytools-3.3-py36_0.tar

**Comment by csmoore** [comment]
Build created to test at: `Solutions\DefenseSolutions\MilitaryToolsForArcGIS\January2019\Dev\182`

Note: Conda package version has been updated to 3.3 in this build:
![image](https://user-images.githubusercontent.com/3090809/51192355-5c1b8c80-18b4-11e9-9024-097e8972858f.png)

**Comment by BobBooth** [comment]
Tested on Pro 2.2.
Used the MT Analysis toolbar tools first, then installed the conda package and tested and the tools from the conda package.
Found that the tools all had appropriate input feature sets.
It seems to me as though the process of populating the output features box took a long time, and overall performance was generally worse for the tools after the Conda install.

**Comment by csmoore** [comment]
After numerous travails trying to clone the pro conda environment ("error cloning"), I was able to install the latest dev-built Military Tools conda package and successfully test this tool with latest build on Pro 2.2 and 2.3 - input and output symbology show up for this tool.

![image](https://user-images.githubusercontent.com/3090809/51215655-a40bd500-18ef-11e9-9c89-2285ebe48384.png)

Tested from dev so removing dev and QC labels

**Comment by lfunkhouser** [comment]
@csmoore The description not showing up was known at 2.2. The team had hoped to push an update to it, but it wasn't critical, so it was planned to show up in 2.3.
