### ISSUE TITLE
Unable to Install Pro 1.4 Add-In for Pro 2.0

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/military-tools-desktop-addins#9]
I'm currently testing military tools in the holistic lab and I was unaware of the fact that our ArcGIS Pro Add-In (built and tested against 1.4) was incompatible with Pro 2.0. When trying to install the Add-In, you get this error message:
![militarytoolspro2 0](https://cloud.githubusercontent.com/assets/13024357/23909943/57c19d7c-0895-11e7-9a1a-180804a8083d.PNG)

If I click yes to continue with the installation, nothing happens, no military tools ribbon appears.

I would expect the Add-In to successfully install in a newer version of Pro (in this case 2.0).

Has anyone else ran into this issue or tried to use military tools in Pro 2.0?
@csmoore @kgonzago any thoughts? 

To reproduce this simply grab the Add-In from our current build location and try and install it on a machine that is currently running Pro 2.0

I tested this with Pro 2.0 both in a disconnected and connected environment, and got the same result. 

@nfeuerstein @lfunkhouser FYI

**Comment by csmoore** [comment]
It is probably just a matter updating the version in the DAML (we should also actually build against 2.0):  

https://github.com/Esri/military-tools-desktop-addins/blob/dev/source/MilitaryToolsForArcGISPro/Config.daml#L3 

I don't recall that warning before - but may have changed at 2.0.  But I would be curious to know from Pro why it doesn't install when you pick "Yes"

**Comment by joebayles** [comment]
@csmoore should we create a new branch for the new version? This DAML update I'm assuming will be a breaking change for anyone trying to use it in 1.4, and therefore would force us to iterate to Military Tools 2.0.

**Comment by csmoore** [comment]
We can ask @ACueva & @kgonzago how they prefer to set up for the 2.0 daily. But simplest might be to just make dev branch target 2.0 if that is what we should be developing against now

**Comment by ACueva** [comment]
I'm thinking "dev" branch should be 2.0,  "master" and "version1.4" branches are 1.4 Final.  Once we have a 2.0 final then "master" and "version2.0" would be 2.0 Final.   Thoughts?

**Comment by joebayles** [comment]
So... 

|Branch|Intent|
|:---:|:---|
|dev|latest version currently being worked on|
|version-1.4|latest build of 1.4|
|version-2.0|latest build of 2.0|

Do we even need a master? Seems like it would be one of those vestigial things that are just a nuisance to update. Or, do we do this:

|Branch|Intent|
|:---:|:---|
|dev|for all dev work|
|version-1.4|latest build of 1.4|
|version-2.0|latest build of 2.0|
|final-1.4|latest _published_ build of 1.4|
|final-2.0|latest _published_ build of 2.0|

Also, should we use Military Tools versioning or ArcGIS Pro versioning? 2.0 would be the same, but not 1.4, it would be 1.0.

**Comment by Dbarnes1** [comment]
lets not worry about versioning in this topic. I think what @ACueva posted makes sense, as we would have a 1.4 branch for updates we make to support 1.4, master stays static until we release the next version of military tools, and dev is for 2.0 dev.

**Comment by ACueva** [comment]
I need to work out how Jenkins will handle different versions of our software.  Perhaps this is the first item of discussion for our Jenkins COP?

**Comment by joebayles** [comment]
Not sure when the Jenkins COP meets, but the one thing I would say is this should happen quickly since code freeze for 2.0 is soon, and we should make sure we don't need anything from them before that.

**Comment by csmoore** [comment]
Closing now that we have 2.0 daily builds of addins. Feel free to re-open if there is something else to do here.
