### ISSUE TITLE
Deleting graphics after initial session

### ISSUE THREAD

**Issue by sindizzy** [Esri/military-tools-desktop-addins#94]
So I use the Distance and Direction Add-In>Rings functionality quite a bit. In Pro I can add rings to a Map view and it works well. However I close the session and open the project later on. My range rings are still there but what if i want to delete and start over or change the color of the graphic. I cannot see any tool that lets me select the graphic in a Map View.

Also when I go to a Layout view I don't think the tool works so shouldn't it be disabled? If you activate a map frame then it should be enabled.

### Your Environment
* Addin Version used:  3.2
* Environment name and version: pro 2.2.4
* Operating System and version: Windows 7 x64 Enterprise

**Comment by csmoore** [comment]
In Pro, the Clear button on the Rings tab should clear any rings created (even if in a previous session) unless there is a bug is a certain scenario.

**Comment by sindizzy** [comment]
It looks like I am still in an edit session. If I close the project and save edits then when I reopen then it appears that there are leftover features in the Distance And Direction dataset. If I zoom in to Range Rings it zooms in to the area where they should be but they are not displayed.

**Comment by csmoore** [comment]
The Clear button should be enabled anytime the Range Rings feature class has features, and yes it does clear out all of the rings/features in the feature class - but it might be a bug (something having to do with the interaction with the Layout view). If you can come up with reproducible steps, can you edit the original issue with the steps to reproduce the problem.

For the rings not show up problem I would just suggest:

1. making sure the Distance and Direction layer is the top most layer and visible 
2. opening the Range Rings feature class in the table view and verify that there is data there.  

I tried opening and closing a project with existing data and it seemed to behave:

![image](https://user-images.githubusercontent.com/3090809/51683136-2151dc80-1fb7-11e9-8adf-ba0fa047cfe4.png)

**Comment by sindizzy** [comment]
It appears the RangeRings feature class is still there but with no features.

**Comment by sindizzy** [comment]
I'll see if I can recreate the issue.

**Comment by lfunkhouser** [comment]
@sindizzy We will continue to try to repro on our end, but if you have steps to reproduce the issue, it would be appreciated if you can provide them.

**Comment by lfunkhouser** [comment]
@sindizzy Wanted to let you know that the capabilities provided with Military Tools for ArcGIS are now available in the newly released ArcGIS Pro 2.6 - available out of the box without an additional install.

**Comment by lfunkhouser** [comment]
Closing this issue as non-reproducible.
