### ISSUE TITLE
Update the doc for installing conda package - add note to update packages

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-desktop-addins#99]
Update the topic, Install the militarytools Python package using the Python Package Manager to update the available versions of militarytools.

Search results return version 3.0 until you refresh.  Add a step to Refresh or update packages to update the list of available packages. 

untools as an example: http://solutions.arcgis.com/utilities/help/utility-network-automation/get-started/install-the-utility-network-package-tools-toolbox.htm 

MT 3.3 January 2019 release
Pro 2.3

**Comment by dfoll** [comment]
- updated MT get started topic

**Comment by dfoll** [comment]
G- Doc (CMS) can be removed when end of day publishing/building tasks are complete

**Comment by dfoll** [comment]
- https://solutionsdev.arcgis.com/defense/help/military-tools/get-started/military-tools-for-arcgis-get-started.htm
- \\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\308\

**Comment by lfunkhouser** [comment]
Verified doc updates on solutionsdev for MT and PDF for MT (dev build 3.5.0.308). Step 2 added to Refresh the list of available packages.
